# Generated by Django 4.1.7 on 2023-04-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_gender_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
